name: Test Calculator

on:
  push:
    branches: [ "MASTER" ]
  pull_request:
    branches: [ "MASTER" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Specify the exact Python version if possible

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          pytest  # Run tests using pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Application
        run: |
          echo "Deploying the application..." # Replace this with actual deployment commands
